In [10]:
import tensorflow as tf

In [11]:
test = tf.Graph()
with test.as_default():
    W1 = tf.Variable(tf.truncated_normal([1,2,2,1],stddev = 0.1))
    W2 = tf.Variable(tf.truncated_normal([1,2,2,1],stddev = 0.1))
    w2conc = tf.Variable(tf.constant(0.1,shape = [1,2]))
    w = tf.reshape(W2, [-1, 4])
    wc = tf.concat([w,w2conc],1)
    saver = tf.train.Saver()

    
with tf.Session(graph = test) as sess:
    tf.global_variables_initializer().run()
    print('W2',sess.run(W2),'\n')
    print('W1',sess.run(W1),'\n')
    sess.run(tf.assign(W2,W1))
    print('W2',sess.run(W2),'\n')
    print('w2conc',sess.run(w2conc),'\n')
    print('w',sess.run(w),'\n')
    print('wc',sess.run(wc),'\n')
    save_path = saver.save(sess, "test/test/model.ckpt")
    print("Model saved in path: %s" % save_path)
    #saver.restore(sess, "test/model.ckpt")
    #print('W2',sess.run(W2),'\n')
    #print('w2conc',sess.run(w2conc),'\n')
    #print('w',sess.run(w),'\n')
    #print('wc',sess.run(wc),'\n')
    print('END')


W2 [[[[ 0.042994  ]
   [-0.18141697]]

  [[-0.04440535]
   [-0.00795977]]]] 

W1 [[[[ 0.08724501]
   [-0.09009444]]

  [[ 0.19615595]
   [-0.04559673]]]] 

W2 [[[[ 0.08724501]
   [-0.09009444]]

  [[ 0.19615595]
   [-0.04559673]]]] 

w2conc [[0.1 0.1]] 

w [[ 0.08724501 -0.09009444  0.19615595 -0.04559673]] 

wc [[ 0.08724501 -0.09009444  0.19615595 -0.04559673  0.1         0.1       ]] 

Model saved in path: test/test/model.ckpt
END


In [8]:
with tf.Session(graph = test) as sess:
    tf.global_variables_initializer().run()
    print('W2',sess.run(W2),'\n')
    print('W1',sess.run(W1),'\n')
    sess.run(tf.assign(W2,W1))
    print('W2',sess.run(W2),'\n')
    print('w2conc',sess.run(w2conc),'\n')
    print('w',sess.run(w),'\n')
    print('wc',sess.run(wc),'\n')
    #save_path = saver.save(sess, "test/model.ckpt")
    #print("Model saved in path: %s" % save_path)
    saver.restore(sess, "test/model.ckpt")
    print('W2',sess.run(W2),'\n')
    print('w2conc',sess.run(w2conc),'\n')
    print('w',sess.run(w),'\n')
    print('wc',sess.run(wc),'\n')
    print('END')


W2 [[[[-0.05310813]
   [-0.12430252]]

  [[-0.04700995]
   [ 0.00236   ]]]] 

W1 [[[[-0.02657912]
   [-0.13984941]]

  [[-0.11922759]
   [-0.06336404]]]] 

W2 [[[[-0.02657912]
   [-0.13984941]]

  [[-0.11922759]
   [-0.06336404]]]] 

w2conc [[0.1 0.1]] 

w [[-0.02657912 -0.13984941 -0.11922759 -0.06336404]] 

wc [[-0.02657912 -0.13984941 -0.11922759 -0.06336404  0.1         0.1       ]] 

INFO:tensorflow:Restoring parameters from test/model.ckpt
W2 [[[[-0.05553719]
   [-0.07537273]]

  [[-0.03040972]
   [ 0.06326277]]]] 

w2conc [[0.1 0.1]] 

w [[-0.05553719 -0.07537273 -0.03040972  0.06326277]] 

wc [[-0.05553719 -0.07537273 -0.03040972  0.06326277  0.1         0.1       ]] 

END
