In [2]:
import tensorflow as tf

In [3]:
test = tf.Graph()
with test.as_default():
    W1 = tf.Variable(tf.truncated_normal([1,2,2,1],stddev = 0.1))
    W2 = tf.Variable(tf.truncated_normal([1,2,2,1],stddev = 0.1))
    w2conc = tf.Variable(tf.constant(0.1,shape = [1,2]))
    w = tf.reshape(W2, [-1, 4])
    wc = tf.concat([w,w2conc],1)
    
    
with tf.Session(graph = test) as sess:
    tf.global_variables_initializer().run()
    print('W2',sess.run(W2),'\n')
    print('W1',sess.run(W1),'\n')
    sess.run(tf.assign(W2,W1))
    print('W2',sess.run(W2),'\n')
    print('w2conc',sess.run(w2conc),'\n')
    print('w',sess.run(w),'\n')
    print('wc',sess.run(wc),'\n')
    print('END')


W2 [[[[0.04644461]
   [0.03409879]]

  [[0.03900358]
   [0.02551108]]]] 

W1 [[[[0.1857396 ]
   [0.03006333]]

  [[0.00361864]
   [0.16596006]]]] 

W2 [[[[0.1857396 ]
   [0.03006333]]

  [[0.00361864]
   [0.16596006]]]] 

w2conc [[0.1 0.1]] 

w [[0.1857396  0.03006333 0.00361864 0.16596006]] 

wc [[0.1857396  0.03006333 0.00361864 0.16596006 0.1        0.1       ]] 

END
