In [1]:
import tensorflow as tf

In [18]:
test = tf.Graph()
with test.as_default():
    W1 = tf.Variable(tf.truncated_normal([1,2,2,1],stddev = 0.1))
    W2 = tf.Variable(tf.truncated_normal([1,2,2,1],stddev = 0.1))
    
with tf.Session(graph = test) as sess:
    tf.global_variables_initializer().run()
    print('W2',sess.run(W2),'\n')
    print('W1',sess.run(W1),'\n')
    sess.run(tf.assign(W2,W1))
    print('W2',sess.run(W2))
    print('END')


W2 [[[[ 0.11614089]
   [ 0.00396085]]

  [[-0.06124334]
   [ 0.02798627]]]] 

W1 [[[[-0.01589333]
   [-0.10400333]]

  [[ 0.06795625]
   [ 0.1650819 ]]]] 

W2 [[[[-0.01589333]
   [-0.10400333]]

  [[ 0.06795625]
   [ 0.1650819 ]]]]
END
